version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: flask run -h 0.0.0.0 -p 5000
    environment:
      FLASK_DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
